#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LOG=/tmp/launchd-oneshot.log

# Append `!` to handle `sh -e`
! read -d '' TEMPLATE << "EOF"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>${job_id}</string>
		<key>EnvironmentVariables</key>
		<dict>
			<key>LAUNCHD_ONESHOT_JOB</key>
			<string>1</string>
		</dict>
		<key>Program</key>
		<string>${launchd_oneshot_bin}</string>
		<key>ProgramArguments</key>
		<array>
			<string>${launchd_oneshot_bin}</string>
			<string>${job}</string>
            <string>${job_type}</string>
		</array>
		<key>RunAtLoad</key>
		<true/>
		<key>KeepAlive</key>
		<dict>
	    <key>SuccessfulExit</key>
	    <false/>
	  </dict>
		<key>StandardOutPath</key>
		<string>${LOG}</string>
		<key>StandardErrorPath</key>
		<string>${LOG}</string>
	</dict>
</plist>

EOF


render_template()
{
  eval "echo \"$(echo "$1")\""
}

job=$1
# Daemons vs Agents, default write jobs as deamons
job_type=${2:-"--daemons"}

if [ ! -x "$job" ];
then
  echo "error: $job is not executable"
  echo
  echo "Usage: launchd-oneshot <job>"
  exit 1
fi

launchd_oneshot_bin=$(/usr/local/bin/realpath "$0")
job=$(/usr/local/bin/realpath "$job") # realpath is installed by `brew install coreutils`
job_id=com.cybertk.launchd-oneshot.$(basename "$job" | tr ' ' '-')

if [[ "$job_type" = "--agents" ]]; then
  launchd_job="/Library/LaunchAgents/$job_id.plist"
else
  launchd_job="/Library/LaunchDaemons/$job_id.plist"
fi

if [ -n "$LAUNCHD_ONESHOT_JOB" ];
then
  # mode: Run job
  eval "$job"
  rc=$?

  if [ "$rc" -eq 0 ]; then
    rm -f "$launchd_job"
    cp "$LOG" "$job.done.log"
    echo "Job done, archived logs at '$job.done.log'"
    # `launchctl unload` will kill this process immediately
    # `launchctl remove` will unload the job
    launchctl remove "$job_id"
    echo "Never reached here"
  fi
  exit "$rc"
fi

# mode: Install job
if [ "$(id -u)" != "0" ];
then
   echo "error: This script must be run as root" 1>&2
   exit 1
fi

render_template "$TEMPLATE" > "$launchd_job"
chmod 644 "$launchd_job"
echo "Installed $1 to $launchd_job"
