#!/bin/sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JOBS_DIR=/usr/local/var/launchd-oneshot/jobs
launchd_oneshot_bin=$(/usr/local/bin/realpath "$0")

LOGS_DIR=/usr/local/var/log/launchd-oneshot

# Parameters
# - job_id
# - launchd_oneshot_bin
# - job
# - log
# Append `!` to handle `sh -e`
! read -d '' TEMPLATE << "EOF"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>${job_id}</string>
		<key>EnvironmentVariables</key>
		<dict>
			<key>LAUNCHD_ONESHOT_JOB</key>
			<string>1</string>
		</dict>
		<key>Program</key>
		<string>${launchd_oneshot_bin}</string>
		<key>ProgramArguments</key>
		<array>
			<string>${launchd_oneshot_bin}</string>
			<string>${job}</string>
		</array>
		<key>RunAtLoad</key>
		<true/>
		<key>KeepAlive</key>
		<dict>
	    <key>SuccessfulExit</key>
	    <false/>
	  </dict>
		<key>StandardOutPath</key>
		<string>${log}</string>
		<key>StandardErrorPath</key>
		<string>${log}</string>
	</dict>
</plist>

EOF


render_template()
{
  eval "echo \"$(echo "$1")\""
}

id_for_job()
{
    declare job=$1
    echo com.cybertk.launchd-oneshot.$job
}

run_job()
{
    declare job=$1

    job_id=$(id_for_job "$job")
    launchd_job="/Library/LaunchDaemons/$job_id.plist"

    eval "$JOBS_DIR/$job"
    rc=$?

    if [[ "$rc" -eq 0 ]]; then
        # Job is complete, cleanup
        rm -f "$launchd_job"
        rm -f "$JOBS_DIR/$job"
        echo "Job done, log can be found at '$LOGS_DIR/$job.log'"
        # `launchctl unload` will kill this process immediately
        # `launchctl remove` will unload the job
        launchctl remove "$job_id"
        echo "Never reached here"
    fi

    exit "$rc"
}

install_job()
{
    declare job_path=$1

    job=$(basename "$job_path" | tr ' ' '-')
    job_id=$(id_for_job "$job")
    launchd_job="/Library/LaunchDaemons/$job_id.plist"
    log="$LOGS_DIR/$job.log"

    if [[ "$(id -u)" != "0" ]]; then
       echo "error: This script must be run as root" 1>&2
       exit 1
    fi

    # Install launchd agents
    render_template "$TEMPLATE" > "$launchd_job"
    chmod 644 "$launchd_job"

    # Install jobs to JOBS_DIR
    cp "$job_path" "$JOBS_DIR/$job"

    echo "Installed launchd agent to $launchd_job"
    echo "Installed job to $JOBS_DIR/$job"
}

main()
{
    declare job=$1

    if [[ -n "$LAUNCHD_ONESHOT_JOB" ]]; then
        run_job "$job"
        exit "$?"
    fi

    job=$(/usr/local/bin/realpath "$job") # realpath is installed by `brew install coreutils`

    if [[ ! -x "$job" ]]; then
        echo "error: $job is not executable"
        echo
        echo "Usage: launchd-oneshot <job>"
        exit 1
    fi

    # Ensure jobs dir is exist
    mkdir -p "$JOBS_DIR" > /dev/null 2>&1
    mkdir -p "$LOGS_DIR" > /dev/null 2>&1

    install_job "$job"
}

main "$@"
